services:

# ПРОПИСЫВАЕМ DJANGO приложение
  web:
    build: . # Для сборка через github(поменяйте коммент на image, если надо с dockerhub)
#    image: ${DOCKER_IMAGE}:${IMAGE_TAG}
#Подгрузка статики, запуск миграцйй и запуск вебсервера для приложения
    command: sh -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput --clear &&
      python manage.py loaddata fixture_tables  fixture_worker&&
      python manage.py create_initial_data &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    # тома для сохранения данных вне контейнера
    volumes:
      - .:/RestOldPalace
      - static_volume:/RestOldPalace/staticfiles
      - media_volume:/RestOldPalace/media
    ports:
      - "8000:8000"
    # условия запуска(не будет работать, пока не запустятся зависимости)
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always # Для автоперезагрузки сервиса на ВМ в случае падения
    #env_file не нужен, т.к. он есть в образе dockerfile и используешь load_dotenv() в коде
      #и файл .env попал в контейнер (через COPY или volumes).
      #прописан condition, так как есть хелвчек в этих контейнерах и сервис включится при условии
      #не только запуска, но и проверки здоровья контейнера (контейнер=0)

  telegram_bot:
    build: .
    command: python telegram_bot.py
    volumes:
      - .:/RestOldPalace
      - media_volume:/RestOldPalace/media  # нужно для отправки скриншотов
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always


# ПРОПИСЫВАЕМ Celery
  worker:
    build: .
    command: celery -A config worker --loglevel=info --pool=eventlet
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/RestOldPalace
    #env_file не нужен, так как файл .env лежит рядом с docker-compose.yml
    #volumes: .:/HabbitTracker → значит, .env доступен → load_dotenv() прочитает его → переменные будут в os.getenv()
    # environment не нужен, так как я ничего не переопределяю и данные берутся из .env


# ПРОПИСЫВАЕМ Celery beat
  beat:
    build: .
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/RestOldPalace
    #env_file не нужен, так как файл .env лежит рядом с docker-compose.yml


# ПРОПИСЫВАЕМ redis
  redis:
    # получаем образ с dockerhub
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always

#ПРОПИСЫВАЕМ ВЕБ СЕРВЕР
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"# если будете настраивать HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/staticfiles
      - media_volume:/media
    depends_on:
      - web
    restart: always

# ПРОПИСЫВАЕМ postgres(db это DB_HOST)
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env #Хоть он лежит рядом, но лучше явно указать
      #Нужен так как мы переопределяем environment и берем
      # данные из .env который лежит рядом - РАБОТА НА УРОВНЕ КОНТЕЙНЕРА, А НЕ DJANGO
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER}"# $$DB_USER если не сработает
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

# Перечисляем имена томов без параметров, которые участвует в работе
volumes:
  postgres_data:
  static_volume:
  media_volume:
