events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;  # ← ЭТО ОБЯЗАТЕЛЬНО
    default_type  application/octet-stream;
    upstream app {
        server web:8000;  # имя сервиса из docker-compose
    }

    server {
        listen 80;
        server_name _;  # или _ для любого

        client_max_body_size 10M;  # Разрешить до 10 МБ загрузки файлов

        location /static/ {
            alias /staticfiles/;
        }

        location /media/ {
            alias /media/;
        }

        location / {
            proxy_pass http://app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}