# Generated by Django 5.2.8 on 2025-11-12 06:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restic", "0004_alter_booking_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="phone_for_unauthorized",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                verbose_name="Телефон (если не авторизован)",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_period",
            field=models.DurationField(
                default=datetime.timedelta(seconds=7200), verbose_name="Длительность"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_time",
            field=models.TimeField(verbose_name="Время начала"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="screenshot",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="bookings/screenshots/",
                verbose_name="Скриншот карты зала",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент (если авторизован)",
            ),
        ),
    ]
