# Generated by Django 5.2.8 on 2025-11-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restic", "0005_booking_phone_for_unauthorized_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=10,
                verbose_name="Сумма",
            ),
        ),
    ]
