# Generated by Django 5.2.8 on 2025-11-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restic", "0006_alter_booking_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время отмены"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_cancelled",
            field=models.BooleanField(default=False, verbose_name="Отменено"),
        ),
    ]
