# Generated by Django 5.2.8 on 2025-11-16 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restic", "0008_booking_guest_first_name_booking_guest_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feedback",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Прочитано"),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создан"),
                            ("check", "На проверке"),
                            ("paid", "Оплачен"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="document/",
                        verbose_name="Чек / скриншот оплаты",
                    ),
                ),
                ("qr_url", models.URLField(blank=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="restic.booking"
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата бронирования",
                "verbose_name_plural": "Оплаты бронирований",
            },
        ),
    ]
