# Generated by Django 5.2.8 on 2025-11-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restic", "0009_booking_is_sold_feedback_is_read_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="qr_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("check", "На проверке"),
                    ("paid", "Оплачен"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
