# Generated by Django 5.2.8 on 2025-11-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restic", "0010_alter_payment_qr_url_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Прочитано"),
        ),
    ]
