# Generated by Django 5.2.8 on 2025-11-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restic", "0011_payment_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("abort", "Отменен"),
                    ("created", "Создан"),
                    ("check", "На проверке"),
                    ("paid", "Оплачен"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
