# Generated by Django 5.2.8 on 2025-11-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restic", "0012_alter_payment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "permissions": [("view_all_bookings", "Может просматривать все брони")],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
    ]
