# Generated by Django 5.2.8 on 2025-11-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restic", "0013_alter_booking_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="telegram_end_notification_sent",
            field=models.BooleanField(
                default=False, verbose_name="Количество отправлений в бота"
            ),
        ),
    ]
