# Generated by Django 5.2.8 on 2025-11-21 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restic", "0014_booking_telegram_end_notification_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("master_chief", "Шеф - повар"),
                            ("su_chief", "Су-шеф"),
                            ("barmen", "Бармен"),
                            ("chief_candy", "Повар-кондитер"),
                            ("chief", "Повар-универсал"),
                            ("oficiant", "Официант"),
                            ("admin", "Администратор"),
                        ],
                        max_length=50,
                        verbose_name="Должность",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("description", models.TextField(verbose_name="Описание сотрудника")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg"],
                                "Только изображения формата png, jpg, jpeg",
                            )
                        ],
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Зарплата"
                    ),
                ),
                ("date_employments", models.DateField(auto_now_add=True)),
                ("date_faired", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
